id: I141CB8CC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T22:05:33+00:00'
last_modified: '2022-06-07T15:11:46.420839+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10015
  title: སྤོ་བོ་གཏེར་སྟོན་བདུད་འདུལ་རྡོ་རྗེ་དང་གནམ་ཆོས་མི་འགྱུར་རྡོ་རྗེའི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    83DE:
      image_group_id: I1KG10023
      title: ''
      total_pages: 193
      order: 1
      base_file: 83DE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
